---
services:
  event-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/ejsadiarin/event-ui:latest
    container_name: event-ui
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://event-api:3001/api
    restart: unless-stopped
    # labels:
    #   # Add these labels for Prometheus to scrape your app
    #   prometheus.io/scrape: "true"
    #   prometheus.io/port: "3000"
    #   prometheus.io/path: "/monitoring/metrics"
